### ISSUE TITLE
Add documentation to block size

### ISSUE THREAD

**Issue by oskarpfeffer** [kdomino/Cumulants.jl#16]
The documentation to the block size is missing and finding it in your paper is not really straightforward, for something that should not be so important for a fast implementation. 
In addition to that you could also handle the univariate problem separately in order to avoid such problems as here:
https://stackoverflow.com/questions/65602034/cannot-figure-out-simple-use-of-cumulants-jl

**Comment by kdomino** [comment]
I have just added some documentation about a block size parameter (and point benchmarking code). Univariate problem can be handled by the code but not efficiently. I will work on the efficient implementation is some time.
