### ISSUE TITLE
Univariate k-statistics ?

### ISSUE THREAD

**Issue by lrnv** [kdomino/Cumulants.jl#18]
Hi, 

Can this package compute univariate fisher's k-statistics from a given vector of samples ? I could not figure it out from the documentation.

**Comment by kdomino** [comment]
Hello.

Univariate moments are of the form m_k = 1/n sum_i(x_i^k), univariate cumulant  c_4 = m_4 - 3c_2^2, c_5 = m_5 - 10c_2*c_3 etc ... (where m_4, m_5 are central moments). 

In this package I do not pay a particular attention to the univariate statistics (and algorithms there are not efficient there). I do not use terms of the form for (n-1) (n-2) for the exact computation of the fisher's k-statistics.

**Comment by lrnv** [comment]
Yes, after posting this question I understood that and finnaly coded up something myself. Thanks anyway :)
